name: bricoloni_v2
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinbox: ^0.13.1
  image_picker: ^1.0.1
  flutter_form_builder: ^7.0.0
  latlong2: ^0.9.0
  geocoding: ^2.1.0
  http: ^1.1.0
  google_maps_flutter: ^2.2.3
  google_fonts : ^4.0.4
  flutter_stripe: ^9.2.1
  flutter_stripe_web: ^4.1.1
  stripe_checkout: ^1.0.1
  pay: ^1.1.0
  jwt_decoder: ^2.0.1
  flutter_web3: ^2.1.9
  web3dart: ^2.6.1
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  web_socket_channel: ^2.4.0
  geolocator: ^8.2.0
  flutter_map: ^4.0.0
  jwt_decode: ^0.3.1
  path_provider: any
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.0
  pdf: any
  url_launcher: any
  image: ^3.0.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets : 
    - lib/images/
    - assets/classifier.tflite
    

